[project]
name = "sekai-assets-updater"
version = "0.1.0"
description = "Update assets of Project Sekai Colorful Stage"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "aiohttp==3.11.14",
    "anyio==4.9.0",
    "olefile==0.47",
    "orjson==3.10.16",
    "pycryptodome==3.22.0",
    "u-msgpack-python==2.8.0",
    "unitypy==1.22.5",
]
