"""Streaming Live GLB preprocessing (extraction-worker GLB roadmap #33).

Everything in this package is inert unless the corresponding feature flags
are enabled; ``ENABLE_STREAMING_LIVE_GLB_PREPROCESSING`` and every narrower
flag default to ``False`` so the standard per-Bundle path is untouched.
"""

from updater.extract.glb.contracts import (
    COMPOSITE_PURPOSE,
    DIAG_DEPENDENCY_CYCLE,
    DIAG_DEPENDENCY_EXCLUDED,
    DIAG_DUPLICATE_BUNDLE,
    DIAG_EDGE_UNKNOWN_BUNDLE,
    DIAG_META_BUNDLE_MISSING,
    DIAG_ROOT_BUNDLE_MISSING,
    DIAG_UNKNOWN_PURPOSE,
    DIAG_UNSAFE_PATH,
    EDGE_ANIMATION,
    EDGE_MEDIA,
    EDGE_METADATA,
    EDGE_REASONS,
    EDGE_ROOT_REFERENCE,
    EDGE_SHADER,
    EDGE_TEXTURE,
    EXTRACTION_PURPOSES,
    GLB_PURPOSES,
    LIVE2D_PURPOSE,
    PLAN_VERSION,
    SCENE3D_PURPOSE,
    SEVERITIES,
    STANDARD_PURPOSE,
    TIMELINE3D_PURPOSE,
    BundleRef,
    DependencyEdge,
    ExcludedDependency,
    ExtractionPlan,
    MissingDependency,
    PlanDiagnostic,
    PlanValidationError,
    RootRef,
    canonical_json_bytes,
    safe_path_segment,
    safe_relative_path,
)
from updater.extract.glb.flags import (
    FLAG_NAMES,
    GLBFlags,
    resolve_glb_flags,
)
from updater.extract.glb.observability import (
    log_plan_built,
    log_plan_diagnostic,
    log_plan_diagnostics,
)

__all__ = [
    "COMPOSITE_PURPOSE",
    "DIAG_DEPENDENCY_CYCLE",
    "DIAG_DEPENDENCY_EXCLUDED",
    "DIAG_DUPLICATE_BUNDLE",
    "DIAG_EDGE_UNKNOWN_BUNDLE",
    "DIAG_META_BUNDLE_MISSING",
    "DIAG_ROOT_BUNDLE_MISSING",
    "DIAG_UNKNOWN_PURPOSE",
    "DIAG_UNSAFE_PATH",
    "EDGE_ANIMATION",
    "EDGE_MEDIA",
    "EDGE_METADATA",
    "EDGE_REASONS",
    "EDGE_ROOT_REFERENCE",
    "EDGE_SHADER",
    "EDGE_TEXTURE",
    "EXTRACTION_PURPOSES",
    "FLAG_NAMES",
    "GLB_PURPOSES",
    "GLBFlags",
    "LIVE2D_PURPOSE",
    "PLAN_VERSION",
    "SCENE3D_PURPOSE",
    "SEVERITIES",
    "STANDARD_PURPOSE",
    "TIMELINE3D_PURPOSE",
    "BundleRef",
    "DependencyEdge",
    "ExcludedDependency",
    "ExtractionPlan",
    "MissingDependency",
    "PlanDiagnostic",
    "PlanValidationError",
    "RootRef",
    "canonical_json_bytes",
    "log_plan_built",
    "log_plan_diagnostic",
    "log_plan_diagnostics",
    "resolve_glb_flags",
    "safe_relative_path",
    "safe_path_segment",
]
